// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type gnutls_uprobeGnutlsAppDataPending struct {
	SessionPtr uint64
	BufferPtr  uint64
	DataLen    uint32
	Direction  uint8
	Pad        [3]uint8
}

type gnutls_uprobeGnutlsPriorityPending struct {
	SessionPtr uint64
	DataPtr    uint64
	Priority   [64]int8
}

type gnutls_uprobeGnutlsSniPending struct {
	SessionPtr uint64
	DataPtr    uint64
	Name       [64]int8
}

// loadGnutls_uprobe returns the embedded CollectionSpec for gnutls_uprobe.
func loadGnutls_uprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Gnutls_uprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load gnutls_uprobe: %w", err)
	}

	return spec, err
}

// loadGnutls_uprobeObjects loads gnutls_uprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*gnutls_uprobeObjects
//	*gnutls_uprobePrograms
//	*gnutls_uprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGnutls_uprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadGnutls_uprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// gnutls_uprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gnutls_uprobeSpecs struct {
	gnutls_uprobeProgramSpecs
	gnutls_uprobeMapSpecs
	gnutls_uprobeVariableSpecs
}

// gnutls_uprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gnutls_uprobeProgramSpecs struct {
	GnutlsGroupGetEnter                    *ebpf.ProgramSpec `ebpf:"gnutls_group_get_enter"`
	GnutlsGroupGetReturn                   *ebpf.ProgramSpec `ebpf:"gnutls_group_get_return"`
	GnutlsHandshakeEnter                   *ebpf.ProgramSpec `ebpf:"gnutls_handshake_enter"`
	GnutlsHandshakeReturn                  *ebpf.ProgramSpec `ebpf:"gnutls_handshake_return"`
	GnutlsPrioritySetDirectEnter           *ebpf.ProgramSpec `ebpf:"gnutls_priority_set_direct_enter"`
	GnutlsPrioritySetDirectReturn          *ebpf.ProgramSpec `ebpf:"gnutls_priority_set_direct_return"`
	GnutlsRecordRecvEnter                  *ebpf.ProgramSpec `ebpf:"gnutls_record_recv_enter"`
	GnutlsRecordRecvReturn                 *ebpf.ProgramSpec `ebpf:"gnutls_record_recv_return"`
	GnutlsRecordSendEnter                  *ebpf.ProgramSpec `ebpf:"gnutls_record_send_enter"`
	GnutlsRecordSendReturn                 *ebpf.ProgramSpec `ebpf:"gnutls_record_send_return"`
	GnutlsServerNameSetEnter               *ebpf.ProgramSpec `ebpf:"gnutls_server_name_set_enter"`
	GnutlsServerNameSetReturn              *ebpf.ProgramSpec `ebpf:"gnutls_server_name_set_return"`
	GnutlsSessionGetVerifyCertStatusEnter  *ebpf.ProgramSpec `ebpf:"gnutls_session_get_verify_cert_status_enter"`
	GnutlsSessionGetVerifyCertStatusReturn *ebpf.ProgramSpec `ebpf:"gnutls_session_get_verify_cert_status_return"`
	GnutlsSessionIsResumedEnter            *ebpf.ProgramSpec `ebpf:"gnutls_session_is_resumed_enter"`
	GnutlsSessionIsResumedReturn           *ebpf.ProgramSpec `ebpf:"gnutls_session_is_resumed_return"`
	GnutlsTransportSetInt2Enter            *ebpf.ProgramSpec `ebpf:"gnutls_transport_set_int2_enter"`
}

// gnutls_uprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gnutls_uprobeMapSpecs struct {
	GnutlsAppDataEvents         *ebpf.MapSpec `ebpf:"gnutls_app_data_events"`
	GnutlsAppDataPending        *ebpf.MapSpec `ebpf:"gnutls_app_data_pending"`
	GnutlsEvents                *ebpf.MapSpec `ebpf:"gnutls_events"`
	GnutlsGroupGetPending       *ebpf.MapSpec `ebpf:"gnutls_group_get_pending"`
	GnutlsPending               *ebpf.MapSpec `ebpf:"gnutls_pending"`
	GnutlsPriorityPending       *ebpf.MapSpec `ebpf:"gnutls_priority_pending"`
	GnutlsSessionResumedPending *ebpf.MapSpec `ebpf:"gnutls_session_resumed_pending"`
	GnutlsSniPending            *ebpf.MapSpec `ebpf:"gnutls_sni_pending"`
	GnutlsVerifyStatusPending   *ebpf.MapSpec `ebpf:"gnutls_verify_status_pending"`
}

// gnutls_uprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gnutls_uprobeVariableSpecs struct {
}

// gnutls_uprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGnutls_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type gnutls_uprobeObjects struct {
	gnutls_uprobePrograms
	gnutls_uprobeMaps
	gnutls_uprobeVariables
}

func (o *gnutls_uprobeObjects) Close() error {
	return _Gnutls_uprobeClose(
		&o.gnutls_uprobePrograms,
		&o.gnutls_uprobeMaps,
	)
}

// gnutls_uprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGnutls_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type gnutls_uprobeMaps struct {
	GnutlsAppDataEvents         *ebpf.Map `ebpf:"gnutls_app_data_events"`
	GnutlsAppDataPending        *ebpf.Map `ebpf:"gnutls_app_data_pending"`
	GnutlsEvents                *ebpf.Map `ebpf:"gnutls_events"`
	GnutlsGroupGetPending       *ebpf.Map `ebpf:"gnutls_group_get_pending"`
	GnutlsPending               *ebpf.Map `ebpf:"gnutls_pending"`
	GnutlsPriorityPending       *ebpf.Map `ebpf:"gnutls_priority_pending"`
	GnutlsSessionResumedPending *ebpf.Map `ebpf:"gnutls_session_resumed_pending"`
	GnutlsSniPending            *ebpf.Map `ebpf:"gnutls_sni_pending"`
	GnutlsVerifyStatusPending   *ebpf.Map `ebpf:"gnutls_verify_status_pending"`
}

func (m *gnutls_uprobeMaps) Close() error {
	return _Gnutls_uprobeClose(
		m.GnutlsAppDataEvents,
		m.GnutlsAppDataPending,
		m.GnutlsEvents,
		m.GnutlsGroupGetPending,
		m.GnutlsPending,
		m.GnutlsPriorityPending,
		m.GnutlsSessionResumedPending,
		m.GnutlsSniPending,
		m.GnutlsVerifyStatusPending,
	)
}

// gnutls_uprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGnutls_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type gnutls_uprobeVariables struct {
}

// gnutls_uprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGnutls_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type gnutls_uprobePrograms struct {
	GnutlsGroupGetEnter                    *ebpf.Program `ebpf:"gnutls_group_get_enter"`
	GnutlsGroupGetReturn                   *ebpf.Program `ebpf:"gnutls_group_get_return"`
	GnutlsHandshakeEnter                   *ebpf.Program `ebpf:"gnutls_handshake_enter"`
	GnutlsHandshakeReturn                  *ebpf.Program `ebpf:"gnutls_handshake_return"`
	GnutlsPrioritySetDirectEnter           *ebpf.Program `ebpf:"gnutls_priority_set_direct_enter"`
	GnutlsPrioritySetDirectReturn          *ebpf.Program `ebpf:"gnutls_priority_set_direct_return"`
	GnutlsRecordRecvEnter                  *ebpf.Program `ebpf:"gnutls_record_recv_enter"`
	GnutlsRecordRecvReturn                 *ebpf.Program `ebpf:"gnutls_record_recv_return"`
	GnutlsRecordSendEnter                  *ebpf.Program `ebpf:"gnutls_record_send_enter"`
	GnutlsRecordSendReturn                 *ebpf.Program `ebpf:"gnutls_record_send_return"`
	GnutlsServerNameSetEnter               *ebpf.Program `ebpf:"gnutls_server_name_set_enter"`
	GnutlsServerNameSetReturn              *ebpf.Program `ebpf:"gnutls_server_name_set_return"`
	GnutlsSessionGetVerifyCertStatusEnter  *ebpf.Program `ebpf:"gnutls_session_get_verify_cert_status_enter"`
	GnutlsSessionGetVerifyCertStatusReturn *ebpf.Program `ebpf:"gnutls_session_get_verify_cert_status_return"`
	GnutlsSessionIsResumedEnter            *ebpf.Program `ebpf:"gnutls_session_is_resumed_enter"`
	GnutlsSessionIsResumedReturn           *ebpf.Program `ebpf:"gnutls_session_is_resumed_return"`
	GnutlsTransportSetInt2Enter            *ebpf.Program `ebpf:"gnutls_transport_set_int2_enter"`
}

func (p *gnutls_uprobePrograms) Close() error {
	return _Gnutls_uprobeClose(
		p.GnutlsGroupGetEnter,
		p.GnutlsGroupGetReturn,
		p.GnutlsHandshakeEnter,
		p.GnutlsHandshakeReturn,
		p.GnutlsPrioritySetDirectEnter,
		p.GnutlsPrioritySetDirectReturn,
		p.GnutlsRecordRecvEnter,
		p.GnutlsRecordRecvReturn,
		p.GnutlsRecordSendEnter,
		p.GnutlsRecordSendReturn,
		p.GnutlsServerNameSetEnter,
		p.GnutlsServerNameSetReturn,
		p.GnutlsSessionGetVerifyCertStatusEnter,
		p.GnutlsSessionGetVerifyCertStatusReturn,
		p.GnutlsSessionIsResumedEnter,
		p.GnutlsSessionIsResumedReturn,
		p.GnutlsTransportSetInt2Enter,
	)
}

func _Gnutls_uprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gnutls_uprobe_bpfel.o
var _Gnutls_uprobeBytes []byte
