// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type go_tls_uprobeGoTlsAppDataPending struct {
	ConnPtr   uint64
	BufferPtr uint64
	DataLen   uint32
	Pad       [4]uint8
}

type go_tls_uprobeGoTlsPidnsConfig struct {
	Dev uint64
	Ino uint64
}

// loadGo_tls_uprobe returns the embedded CollectionSpec for go_tls_uprobe.
func loadGo_tls_uprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Go_tls_uprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load go_tls_uprobe: %w", err)
	}

	return spec, err
}

// loadGo_tls_uprobeObjects loads go_tls_uprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*go_tls_uprobeObjects
//	*go_tls_uprobePrograms
//	*go_tls_uprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGo_tls_uprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadGo_tls_uprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// go_tls_uprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type go_tls_uprobeSpecs struct {
	go_tls_uprobeProgramSpecs
	go_tls_uprobeMapSpecs
	go_tls_uprobeVariableSpecs
}

// go_tls_uprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type go_tls_uprobeProgramSpecs struct {
	GoTlsClientHandshakeEnter *ebpf.ProgramSpec `ebpf:"go_tls_client_handshake_enter"`
	GoTlsConnectionState      *ebpf.ProgramSpec `ebpf:"go_tls_connection_state"`
	GoTlsReadEnter            *ebpf.ProgramSpec `ebpf:"go_tls_read_enter"`
	GoTlsReadReturn           *ebpf.ProgramSpec `ebpf:"go_tls_read_return"`
	GoTlsServerHandshakeEnter *ebpf.ProgramSpec `ebpf:"go_tls_server_handshake_enter"`
	GoTlsWriteEnter           *ebpf.ProgramSpec `ebpf:"go_tls_write_enter"`
	GoTlsWriteReturn          *ebpf.ProgramSpec `ebpf:"go_tls_write_return"`
}

// go_tls_uprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type go_tls_uprobeMapSpecs struct {
	GoTlsAppDataEvents  *ebpf.MapSpec `ebpf:"go_tls_app_data_events"`
	GoTlsEvents         *ebpf.MapSpec `ebpf:"go_tls_events"`
	GoTlsPidnsConfigMap *ebpf.MapSpec `ebpf:"go_tls_pidns_config_map"`
	GoTlsReadPending    *ebpf.MapSpec `ebpf:"go_tls_read_pending"`
	GoTlsWritePending   *ebpf.MapSpec `ebpf:"go_tls_write_pending"`
}

// go_tls_uprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type go_tls_uprobeVariableSpecs struct {
}

// go_tls_uprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGo_tls_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type go_tls_uprobeObjects struct {
	go_tls_uprobePrograms
	go_tls_uprobeMaps
	go_tls_uprobeVariables
}

func (o *go_tls_uprobeObjects) Close() error {
	return _Go_tls_uprobeClose(
		&o.go_tls_uprobePrograms,
		&o.go_tls_uprobeMaps,
	)
}

// go_tls_uprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGo_tls_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type go_tls_uprobeMaps struct {
	GoTlsAppDataEvents  *ebpf.Map `ebpf:"go_tls_app_data_events"`
	GoTlsEvents         *ebpf.Map `ebpf:"go_tls_events"`
	GoTlsPidnsConfigMap *ebpf.Map `ebpf:"go_tls_pidns_config_map"`
	GoTlsReadPending    *ebpf.Map `ebpf:"go_tls_read_pending"`
	GoTlsWritePending   *ebpf.Map `ebpf:"go_tls_write_pending"`
}

func (m *go_tls_uprobeMaps) Close() error {
	return _Go_tls_uprobeClose(
		m.GoTlsAppDataEvents,
		m.GoTlsEvents,
		m.GoTlsPidnsConfigMap,
		m.GoTlsReadPending,
		m.GoTlsWritePending,
	)
}

// go_tls_uprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGo_tls_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type go_tls_uprobeVariables struct {
}

// go_tls_uprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGo_tls_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type go_tls_uprobePrograms struct {
	GoTlsClientHandshakeEnter *ebpf.Program `ebpf:"go_tls_client_handshake_enter"`
	GoTlsConnectionState      *ebpf.Program `ebpf:"go_tls_connection_state"`
	GoTlsReadEnter            *ebpf.Program `ebpf:"go_tls_read_enter"`
	GoTlsReadReturn           *ebpf.Program `ebpf:"go_tls_read_return"`
	GoTlsServerHandshakeEnter *ebpf.Program `ebpf:"go_tls_server_handshake_enter"`
	GoTlsWriteEnter           *ebpf.Program `ebpf:"go_tls_write_enter"`
	GoTlsWriteReturn          *ebpf.Program `ebpf:"go_tls_write_return"`
}

func (p *go_tls_uprobePrograms) Close() error {
	return _Go_tls_uprobeClose(
		p.GoTlsClientHandshakeEnter,
		p.GoTlsConnectionState,
		p.GoTlsReadEnter,
		p.GoTlsReadReturn,
		p.GoTlsServerHandshakeEnter,
		p.GoTlsWriteEnter,
		p.GoTlsWriteReturn,
	)
}

func _Go_tls_uprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed go_tls_uprobe_bpfeb.o
var _Go_tls_uprobeBytes []byte
