// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type openssl_uprobeOpensslAppDataPending struct {
	SessionPtr uint64
	BufferPtr  uint64
	DataLen    uint32
	Direction  uint8
	Pad        [3]uint8
}

type openssl_uprobeOpensslFdPending struct {
	SessionPtr uint64
	Fd         int32
	Pad        uint32
}

type openssl_uprobeOpensslGroupsPending struct {
	SessionPtr uint64
	Groups     [64]int8
}

type openssl_uprobeOpensslPendingKey struct {
	PidTgid   uint64
	ProbeKind uint8
	Pad       [7]uint8
}

type openssl_uprobeOpensslSniPending struct {
	SessionPtr uint64
	Name       [64]int8
}

// loadOpenssl_uprobe returns the embedded CollectionSpec for openssl_uprobe.
func loadOpenssl_uprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Openssl_uprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load openssl_uprobe: %w", err)
	}

	return spec, err
}

// loadOpenssl_uprobeObjects loads openssl_uprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*openssl_uprobeObjects
//	*openssl_uprobePrograms
//	*openssl_uprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpenssl_uprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpenssl_uprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// openssl_uprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openssl_uprobeSpecs struct {
	openssl_uprobeProgramSpecs
	openssl_uprobeMapSpecs
	openssl_uprobeVariableSpecs
}

// openssl_uprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openssl_uprobeProgramSpecs struct {
	OpensslSslAcceptEnter              *ebpf.ProgramSpec `ebpf:"openssl_ssl_accept_enter"`
	OpensslSslAcceptReturn             *ebpf.ProgramSpec `ebpf:"openssl_ssl_accept_return"`
	OpensslSslConnectEnter             *ebpf.ProgramSpec `ebpf:"openssl_ssl_connect_enter"`
	OpensslSslConnectReturn            *ebpf.ProgramSpec `ebpf:"openssl_ssl_connect_return"`
	OpensslSslCtrlEnter                *ebpf.ProgramSpec `ebpf:"openssl_ssl_ctrl_enter"`
	OpensslSslCtrlReturn               *ebpf.ProgramSpec `ebpf:"openssl_ssl_ctrl_return"`
	OpensslSslDoHandshakeEnter         *ebpf.ProgramSpec `ebpf:"openssl_ssl_do_handshake_enter"`
	OpensslSslDoHandshakeReturn        *ebpf.ProgramSpec `ebpf:"openssl_ssl_do_handshake_return"`
	OpensslSslGetNegotiatedGroupEnter  *ebpf.ProgramSpec `ebpf:"openssl_ssl_get_negotiated_group_enter"`
	OpensslSslGetNegotiatedGroupReturn *ebpf.ProgramSpec `ebpf:"openssl_ssl_get_negotiated_group_return"`
	OpensslSslGetVerifyResultEnter     *ebpf.ProgramSpec `ebpf:"openssl_ssl_get_verify_result_enter"`
	OpensslSslGetVerifyResultReturn    *ebpf.ProgramSpec `ebpf:"openssl_ssl_get_verify_result_return"`
	OpensslSslKeylogSecretEnter        *ebpf.ProgramSpec `ebpf:"openssl_ssl_keylog_secret_enter"`
	OpensslSslReadEnter                *ebpf.ProgramSpec `ebpf:"openssl_ssl_read_enter"`
	OpensslSslReadReturn               *ebpf.ProgramSpec `ebpf:"openssl_ssl_read_return"`
	OpensslSslSessionReusedEnter       *ebpf.ProgramSpec `ebpf:"openssl_ssl_session_reused_enter"`
	OpensslSslSessionReusedReturn      *ebpf.ProgramSpec `ebpf:"openssl_ssl_session_reused_return"`
	OpensslSslSetFdEnter               *ebpf.ProgramSpec `ebpf:"openssl_ssl_set_fd_enter"`
	OpensslSslSetFdReturn              *ebpf.ProgramSpec `ebpf:"openssl_ssl_set_fd_return"`
	OpensslSslSetGroupsListEnter       *ebpf.ProgramSpec `ebpf:"openssl_ssl_set_groups_list_enter"`
	OpensslSslSetGroupsListReturn      *ebpf.ProgramSpec `ebpf:"openssl_ssl_set_groups_list_return"`
	OpensslSslSetVerifyEnter           *ebpf.ProgramSpec `ebpf:"openssl_ssl_set_verify_enter"`
	OpensslSslWriteEnter               *ebpf.ProgramSpec `ebpf:"openssl_ssl_write_enter"`
	OpensslSslWriteReturn              *ebpf.ProgramSpec `ebpf:"openssl_ssl_write_return"`
}

// openssl_uprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openssl_uprobeMapSpecs struct {
	OpensslAppDataEvents          *ebpf.MapSpec `ebpf:"openssl_app_data_events"`
	OpensslAppDataPending         *ebpf.MapSpec `ebpf:"openssl_app_data_pending"`
	OpensslEvents                 *ebpf.MapSpec `ebpf:"openssl_events"`
	OpensslFdPending              *ebpf.MapSpec `ebpf:"openssl_fd_pending"`
	OpensslGroupsPending          *ebpf.MapSpec `ebpf:"openssl_groups_pending"`
	OpensslNegotiatedGroupPending *ebpf.MapSpec `ebpf:"openssl_negotiated_group_pending"`
	OpensslPending                *ebpf.MapSpec `ebpf:"openssl_pending"`
	OpensslSessionReusedPending   *ebpf.MapSpec `ebpf:"openssl_session_reused_pending"`
	OpensslSniPending             *ebpf.MapSpec `ebpf:"openssl_sni_pending"`
	OpensslVerifyResultPending    *ebpf.MapSpec `ebpf:"openssl_verify_result_pending"`
}

// openssl_uprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openssl_uprobeVariableSpecs struct {
}

// openssl_uprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpenssl_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type openssl_uprobeObjects struct {
	openssl_uprobePrograms
	openssl_uprobeMaps
	openssl_uprobeVariables
}

func (o *openssl_uprobeObjects) Close() error {
	return _Openssl_uprobeClose(
		&o.openssl_uprobePrograms,
		&o.openssl_uprobeMaps,
	)
}

// openssl_uprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpenssl_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type openssl_uprobeMaps struct {
	OpensslAppDataEvents          *ebpf.Map `ebpf:"openssl_app_data_events"`
	OpensslAppDataPending         *ebpf.Map `ebpf:"openssl_app_data_pending"`
	OpensslEvents                 *ebpf.Map `ebpf:"openssl_events"`
	OpensslFdPending              *ebpf.Map `ebpf:"openssl_fd_pending"`
	OpensslGroupsPending          *ebpf.Map `ebpf:"openssl_groups_pending"`
	OpensslNegotiatedGroupPending *ebpf.Map `ebpf:"openssl_negotiated_group_pending"`
	OpensslPending                *ebpf.Map `ebpf:"openssl_pending"`
	OpensslSessionReusedPending   *ebpf.Map `ebpf:"openssl_session_reused_pending"`
	OpensslSniPending             *ebpf.Map `ebpf:"openssl_sni_pending"`
	OpensslVerifyResultPending    *ebpf.Map `ebpf:"openssl_verify_result_pending"`
}

func (m *openssl_uprobeMaps) Close() error {
	return _Openssl_uprobeClose(
		m.OpensslAppDataEvents,
		m.OpensslAppDataPending,
		m.OpensslEvents,
		m.OpensslFdPending,
		m.OpensslGroupsPending,
		m.OpensslNegotiatedGroupPending,
		m.OpensslPending,
		m.OpensslSessionReusedPending,
		m.OpensslSniPending,
		m.OpensslVerifyResultPending,
	)
}

// openssl_uprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOpenssl_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type openssl_uprobeVariables struct {
}

// openssl_uprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpenssl_uprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type openssl_uprobePrograms struct {
	OpensslSslAcceptEnter              *ebpf.Program `ebpf:"openssl_ssl_accept_enter"`
	OpensslSslAcceptReturn             *ebpf.Program `ebpf:"openssl_ssl_accept_return"`
	OpensslSslConnectEnter             *ebpf.Program `ebpf:"openssl_ssl_connect_enter"`
	OpensslSslConnectReturn            *ebpf.Program `ebpf:"openssl_ssl_connect_return"`
	OpensslSslCtrlEnter                *ebpf.Program `ebpf:"openssl_ssl_ctrl_enter"`
	OpensslSslCtrlReturn               *ebpf.Program `ebpf:"openssl_ssl_ctrl_return"`
	OpensslSslDoHandshakeEnter         *ebpf.Program `ebpf:"openssl_ssl_do_handshake_enter"`
	OpensslSslDoHandshakeReturn        *ebpf.Program `ebpf:"openssl_ssl_do_handshake_return"`
	OpensslSslGetNegotiatedGroupEnter  *ebpf.Program `ebpf:"openssl_ssl_get_negotiated_group_enter"`
	OpensslSslGetNegotiatedGroupReturn *ebpf.Program `ebpf:"openssl_ssl_get_negotiated_group_return"`
	OpensslSslGetVerifyResultEnter     *ebpf.Program `ebpf:"openssl_ssl_get_verify_result_enter"`
	OpensslSslGetVerifyResultReturn    *ebpf.Program `ebpf:"openssl_ssl_get_verify_result_return"`
	OpensslSslKeylogSecretEnter        *ebpf.Program `ebpf:"openssl_ssl_keylog_secret_enter"`
	OpensslSslReadEnter                *ebpf.Program `ebpf:"openssl_ssl_read_enter"`
	OpensslSslReadReturn               *ebpf.Program `ebpf:"openssl_ssl_read_return"`
	OpensslSslSessionReusedEnter       *ebpf.Program `ebpf:"openssl_ssl_session_reused_enter"`
	OpensslSslSessionReusedReturn      *ebpf.Program `ebpf:"openssl_ssl_session_reused_return"`
	OpensslSslSetFdEnter               *ebpf.Program `ebpf:"openssl_ssl_set_fd_enter"`
	OpensslSslSetFdReturn              *ebpf.Program `ebpf:"openssl_ssl_set_fd_return"`
	OpensslSslSetGroupsListEnter       *ebpf.Program `ebpf:"openssl_ssl_set_groups_list_enter"`
	OpensslSslSetGroupsListReturn      *ebpf.Program `ebpf:"openssl_ssl_set_groups_list_return"`
	OpensslSslSetVerifyEnter           *ebpf.Program `ebpf:"openssl_ssl_set_verify_enter"`
	OpensslSslWriteEnter               *ebpf.Program `ebpf:"openssl_ssl_write_enter"`
	OpensslSslWriteReturn              *ebpf.Program `ebpf:"openssl_ssl_write_return"`
}

func (p *openssl_uprobePrograms) Close() error {
	return _Openssl_uprobeClose(
		p.OpensslSslAcceptEnter,
		p.OpensslSslAcceptReturn,
		p.OpensslSslConnectEnter,
		p.OpensslSslConnectReturn,
		p.OpensslSslCtrlEnter,
		p.OpensslSslCtrlReturn,
		p.OpensslSslDoHandshakeEnter,
		p.OpensslSslDoHandshakeReturn,
		p.OpensslSslGetNegotiatedGroupEnter,
		p.OpensslSslGetNegotiatedGroupReturn,
		p.OpensslSslGetVerifyResultEnter,
		p.OpensslSslGetVerifyResultReturn,
		p.OpensslSslKeylogSecretEnter,
		p.OpensslSslReadEnter,
		p.OpensslSslReadReturn,
		p.OpensslSslSessionReusedEnter,
		p.OpensslSslSessionReusedReturn,
		p.OpensslSslSetFdEnter,
		p.OpensslSslSetFdReturn,
		p.OpensslSslSetGroupsListEnter,
		p.OpensslSslSetGroupsListReturn,
		p.OpensslSslSetVerifyEnter,
		p.OpensslSslWriteEnter,
		p.OpensslSslWriteReturn,
	)
}

func _Openssl_uprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed openssl_uprobe_bpfeb.o
var _Openssl_uprobeBytes []byte
