// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadProcess_events returns the embedded CollectionSpec for process_events.
func loadProcess_events() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Process_eventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process_events: %w", err)
	}

	return spec, err
}

// loadProcess_eventsObjects loads process_events and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*process_eventsObjects
//	*process_eventsPrograms
//	*process_eventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcess_eventsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess_events()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// process_eventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_eventsSpecs struct {
	process_eventsProgramSpecs
	process_eventsMapSpecs
	process_eventsVariableSpecs
}

// process_eventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_eventsProgramSpecs struct {
	ProcessExec *ebpf.ProgramSpec `ebpf:"process_exec"`
	ProcessExit *ebpf.ProgramSpec `ebpf:"process_exit"`
}

// process_eventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_eventsMapSpecs struct {
	ProcessEvents *ebpf.MapSpec `ebpf:"process_events"`
}

// process_eventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type process_eventsVariableSpecs struct {
}

// process_eventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcess_eventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_eventsObjects struct {
	process_eventsPrograms
	process_eventsMaps
	process_eventsVariables
}

func (o *process_eventsObjects) Close() error {
	return _Process_eventsClose(
		&o.process_eventsPrograms,
		&o.process_eventsMaps,
	)
}

// process_eventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcess_eventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_eventsMaps struct {
	ProcessEvents *ebpf.Map `ebpf:"process_events"`
}

func (m *process_eventsMaps) Close() error {
	return _Process_eventsClose(
		m.ProcessEvents,
	)
}

// process_eventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcess_eventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_eventsVariables struct {
}

// process_eventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcess_eventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type process_eventsPrograms struct {
	ProcessExec *ebpf.Program `ebpf:"process_exec"`
	ProcessExit *ebpf.Program `ebpf:"process_exit"`
}

func (p *process_eventsPrograms) Close() error {
	return _Process_eventsClose(
		p.ProcessExec,
		p.ProcessExit,
	)
}

func _Process_eventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_events_bpfel.o
var _Process_eventsBytes []byte
